version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - server_vol:/config
    
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Santiago Lionel
      - CLI_SURNAME=Lorca
      - CLI_GAMBLER_ID=30904465
      - CLI_BIRTHDATE=1999-03-17
      - CLI_NUMBER=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - client_vol:/config
    
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Juan
      - CLI_SURNAME=Perez
      - CLI_GAMBLER_ID=34789124
      - CLI_BIRTHDATE=1998-05-12
      - CLI_NUMBER=3142
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - client_vol:/config
    
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Lucia Jazmin
      - CLI_SURNAME=Rodriguez
      - CLI_GAMBLER_ID=38901234
      - CLI_BIRTHDATE=2000-12-25
      - CLI_NUMBER=5678
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - client_vol:/config
    
  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Carlos Miguel
      - CLI_SURNAME=Sanchez
      - CLI_GAMBLER_ID=39876543
      - CLI_BIRTHDATE=1997-08-30
      - CLI_NUMBER=7890
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - client_vol:/config
    
  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Ana Maria
      - CLI_SURNAME=Alvarez
      - CLI_GAMBLER_ID=40901234
      - CLI_BIRTHDATE=2001-12-25
      - CLI_NUMBER=1890
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - client_vol:/config
    
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
volumes:
  server_vol:
    driver: local
    driver_opts:
      type: none
      device: ./server/config
      o: bind
  client_vol:
    driver: local
    driver_opts:
      type: none
      device: ./client/config
      o: bind
